#!/bin/bash

_link () {
    if [[ ! -e $2 ]]; then
        echo -e "\tCreating $2..."
        ln -ns $1 $2
    else
        if [[ -L $2 && $(python3 -c "import os; print(os.readlink('$2'))") == "$1" ]]; then
            echo -e "\t$2 is already correct, skipping."
        else
            echo -e "\tFile already exists at $2, please move it aside first!"
            failed=1
        fi
    fi
}

failed=0

if ! command -v "python3" &> /dev/null; then
    echo "ERROR: Python 3 must be installed."
    exit 1
fi

echo -n "Calculating install dir... "
ourdir=$(dirname $BASH_SOURCE)
if [ $ourdir == '.' ]; then
    ourdir=$(pwd)
fi
rel=$(python3 -c "import os.path; print(os.path.relpath('$ourdir', '$HOME'))")
echo "~/$rel"

echo "Installing symlinks..."

# Generic symlinks in ~
for source in tmux.conf vim vimrc zsh zshrc zshrc.local zshrc.pre; do
    _link $rel/$source $HOME/.$source
done

# XDG symlinks
mkdir -p $HOME/.config
for source in nvim ghostty; do
    _link ../$rel/config/$source $HOME/.config/$source
done

echo "Fetching submodules..."
git -C $ourdir submodule update --init

echo "Making cache directories..."
mkdir -p ~/.cache/vim/backup
mkdir -p ~/.cache/vim/swap
mkdir -p ~/.cache/vim/undo

if [[ "$(uname -s)" == "Darwin" ]]; then
    echo "Darwin: Disabling login notifications..."
    touch ~/.hushlogin
fi

echo "Done."

if [ $failed -eq 1 ]; then
    exit 1
fi
